# fly.toml app configuration file generated for full-stack-open-cicd-example-project on 2024-11-27T14:09:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglist-ci-cd-weathered-sun-4591'
primary_region = 'gru'

[build]

[env]
  PORT = "3003"

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"
  protocol = "http"

[deploy]
  strategy = "canary"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
